### ISSUE TITLE
notification bar issue during calls

### ISSUE THREAD

**Issue by MVF4** [Exynos7420/android_device_samsung_zero-common#3]
I tested the last revision of lineageos 17 (LineageOS-10-zero-multitarget-2020-02-28_1703) and lineageos 16 (LineageOS-9-zero-multitarget-2020-01-21_1526) and I have found the same issue on my samsung s6 sm-g920f.
During calls, holding the phone near my face, the proximity sensor turns off the display to prevent keypad presses. The issue is that, under the black screen, the notification bar can be pulled down and the related buttons may be pressed, despite the screen is black.
Now I'm using lineage 15.1 which hasn't this issue and works properly, even if it has other issues (volume too low of camera mic during recording, and other problems).
Thank you.

**Comment by enesuzun2002** [comment]
https://github.com/Exynos7420/android_device_samsung_zero-common/commit/d12e23c6d8e33727a7d3fc9b287b225c87b7012a#diff-c2366e35d3e9e25b01d19e54bd0b5e25

**Comment by enesuzun2002** [comment]
It is fixed for 17.1 and it will be merged to 16.0 soon.

**Comment by MVF4** [comment]
I have installed  the new release LineageOS-10-zero-multitarget-2020-04-13_2047 but the issue is still present. Nothing changed: under the black screen, the notification bar can be pulled down and the related buttons may be pressed.

**Comment by enesuzun2002** [comment]
please disable DT2W

**Comment by MVF4** [comment]
Many thanks for the answer! But yesterday I have re-installed lineage-15.1-20190712-UNOFFICIAL-zerofltexx, even if  lineage-15.1-20190712 has an annoying problem: the volume is too low on video recordings. I take advantage of your kindness, is there a smart solution to this issue on lineageos 15.1? I have tried to increase the gain-camcorder-mic and the gain-media-mic on the Mixer_paths_0.xml file but nothing changed. Thanks.
